-- MySQL Script generated by MySQL Workbench
-- mar 06 jun 2023 08:07:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Resultados_ICFES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Resultados_ICFES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Resultados_ICFES` (
  `codigo_icfes` INT UNSIGNED NOT NULL,
  `resultado_icfes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo_icfes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aspirante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aspirante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aspirante` (
  `id_aspirante` INT UNSIGNED NOT NULL,
  `id_tipo_aspirante` VARCHAR(45) NOT NULL,
  `nombre_aspirante` VARCHAR(45) NOT NULL,
  `apellido_aspirante` VARCHAR(45) NOT NULL,
  `correo_personal_aspirante` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `departamento_aspirante` VARCHAR(45) NOT NULL,
  `ciudad_aspirante` VARCHAR(45) NOT NULL,
  `estrato_apirante` INT UNSIGNED NOT NULL,
  `codigo_icfes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_aspirante`),
  CONSTRAINT `fk_Aspirante_Resultados_ICFES1`
    FOREIGN KEY (`codigo_icfes`)
    REFERENCES `mydb`.`Resultados_ICFES` (`codigo_icfes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `correo_personal_aspirante_UNIQUE` ON `mydb`.`Aspirante` (`correo_personal_aspirante` ASC) VISIBLE;

CREATE INDEX `fk_Aspirante_Resultados_ICFES1_idx` ON `mydb`.`Aspirante` (`codigo_icfes` ASC) VISIBLE;

CREATE UNIQUE INDEX `codigo_icfes_UNIQUE` ON `mydb`.`Aspirante` (`codigo_icfes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Sede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sede` (
  `nombre_sede` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facultad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Facultad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Facultad` (
  `id_facultad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_sede` VARCHAR(45) NOT NULL,
  `nombre_facultad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_facultad`, `nombre_sede`),
  CONSTRAINT `fk_Facultad_Sede1`
    FOREIGN KEY (`nombre_sede`)
    REFERENCES `mydb`.`Sede` (`nombre_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Facultad_Sede1_idx` ON `mydb`.`Facultad` (`nombre_sede` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Convocatoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Convocatoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Convocatoria` (
  `id_convocatoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `anno_convocatoria` INT UNSIGNED NOT NULL,
  `semestre_convocatoria` INT UNSIGNED NOT NULL,
  `fecha_prueba_admision` DATETIME NOT NULL,
  PRIMARY KEY (`id_convocatoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Convocatoria_pregrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Convocatoria_pregrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Convocatoria_pregrado` (
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `tipo_convocatoria_pregrado` VARCHAR(45) NOT NULL,
  `puntaje_minimo_admision_convocatoria_pregrado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_convocatoria`),
  CONSTRAINT `fk_Convocatoria_pregrado_Convocatoria1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Convocatoria_pregrado_Convocatoria1_idx` ON `mydb`.`Convocatoria_pregrado` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Programa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Programa` (
  `id_programa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_facultad_programa` INT UNSIGNED NOT NULL,
  `nombre_programa` VARCHAR(45) NOT NULL,
  `cupos_programa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_programa`),
  CONSTRAINT `fk_Programa_Facultad1`
    FOREIGN KEY (`id_facultad_programa`)
    REFERENCES `mydb`.`Facultad` (`id_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Programa_Convocatoria_pregrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_pregrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Programa_Facultad1_idx` ON `mydb`.`Programa` (`id_facultad_programa` ASC) VISIBLE;

CREATE INDEX `fk_Programa_Convocatoria_pregrado1_idx` ON `mydb`.`Programa` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitud_admision_pregrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Solicitud_admision_pregrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Solicitud_admision_pregrado` (
  `id_solicitud_admision_pregrado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `Aspirante_id_aspirante` INT UNSIGNED NOT NULL,
  `presenta_examen_musica` VARCHAR(2) NOT NULL,
  `presenta_examen_cine_y_television` VARCHAR(2) NOT NULL,
  `presenta_examen_artes_plasticas` VARCHAR(2) NOT NULL,
  `presenta_simulacro_extrajero` VARCHAR(2) NOT NULL,
  `nombre_sede` VARCHAR(45) NOT NULL,
  `id_programa` INT UNSIGNED NOT NULL,
  `id_programa_secundario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_solicitud_admision_pregrado`),
  CONSTRAINT `fk_Solicitud_admision_Aspirante1`
    FOREIGN KEY (`Aspirante_id_aspirante`)
    REFERENCES `mydb`.`Aspirante` (`id_aspirante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_admision_Programa1`
    FOREIGN KEY (`id_programa`)
    REFERENCES `mydb`.`Programa` (`id_programa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_admision_Programa2`
    FOREIGN KEY (`id_programa_secundario`)
    REFERENCES `mydb`.`Programa` (`id_programa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_admision_Convocatoria_pregrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_pregrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_admision_Sede1`
    FOREIGN KEY (`nombre_sede`)
    REFERENCES `mydb`.`Sede` (`nombre_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Solicitud_admision_Aspirante1_idx` ON `mydb`.`Solicitud_admision_pregrado` (`Aspirante_id_aspirante` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_admision_Programa1_idx` ON `mydb`.`Solicitud_admision_pregrado` (`id_programa` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_admision_Programa2_idx` ON `mydb`.`Solicitud_admision_pregrado` (`id_programa_secundario` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_admision_Convocatoria_pregrado1_idx` ON `mydb`.`Solicitud_admision_pregrado` (`id_convocatoria` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_admision_Sede1_idx` ON `mydb`.`Solicitud_admision_pregrado` (`nombre_sede` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Lugar_prueba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lugar_prueba` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lugar_prueba` (
  `id_lugar_prueba` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_lugar_prueba` VARCHAR(45) NOT NULL,
  `departamento_lugar_prueba` VARCHAR(45) NOT NULL,
  `ciudad_lugar_prueba` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lugar_prueba`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Especificacion_lugar_prueba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Especificacion_lugar_prueba` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Especificacion_lugar_prueba` (
  `id_lugar_prueba` INT UNSIGNED NOT NULL,
  `descripcion_especifica_lugar_prueba` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lugar_prueba`, `descripcion_especifica_lugar_prueba`),
  CONSTRAINT `fk_Especificacion_lugar_Lugar_prueba1`
    FOREIGN KEY (`id_lugar_prueba`)
    REFERENCES `mydb`.`Lugar_prueba` (`id_lugar_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Convocatoria_musica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Convocatoria_musica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Convocatoria_musica` (
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `nota_pasar_prueba_1` INT UNSIGNED NOT NULL,
  `nota_pasar_prueba_2` INT UNSIGNED NOT NULL,
  `nota_pasar_prueba_3` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_convocatoria`),
  CONSTRAINT `fk_Convocatoria_musica_Convocatoria_pregrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_pregrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pruebas_musica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pruebas_musica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pruebas_musica` (
  `id_pruebas_musica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_solicitud_admision` INT UNSIGNED NOT NULL,
  `resultado_prueba_1` INT UNSIGNED NULL,
  `resultado_prueba_2` INT UNSIGNED NULL,
  `resultado_prueba_3` INT UNSIGNED NULL,
  `id_lugar_prueba_1` INT UNSIGNED NOT NULL,
  `descripcion_especifica_lugar_prueba_1` VARCHAR(45) NOT NULL,
  `fecha_y_hora_prueba_musica_1` DATETIME NULL,
  `id_lugar_prueba_2` INT UNSIGNED NULL,
  `descripcion_especifica_lugar_prueba_2` VARCHAR(45) NULL,
  `fecha_y_hora_prueba_musica_2` DATETIME NULL,
  `id_lugar_prueba_3` INT UNSIGNED NULL,
  `descripcion_especifica_lugar_prueba_3` VARCHAR(45) NULL,
  `fecha_y_hora_prueba_musica_3` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pruebas_musica`),
  CONSTRAINT `fk_Pruebas_Musica_Solicitud_admision1`
    FOREIGN KEY (`id_solicitud_admision`)
    REFERENCES `mydb`.`Solicitud_admision_pregrado` (`id_solicitud_admision_pregrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pruebas_musica_Especificacion_lugar_prueba1`
    FOREIGN KEY (`id_lugar_prueba_1` , `descripcion_especifica_lugar_prueba_1`)
    REFERENCES `mydb`.`Especificacion_lugar_prueba` (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pruebas_musica_Especificacion_lugar_prueba2`
    FOREIGN KEY (`id_lugar_prueba_2` , `descripcion_especifica_lugar_prueba_2`)
    REFERENCES `mydb`.`Especificacion_lugar_prueba` (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pruebas_musica_Especificacion_lugar_prueba3`
    FOREIGN KEY (`id_lugar_prueba_3` , `descripcion_especifica_lugar_prueba_3`)
    REFERENCES `mydb`.`Especificacion_lugar_prueba` (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pruebas_musica_Convocatoria_musica1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_musica` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pruebas_Musica_Solicitud_admision1_idx` ON `mydb`.`Pruebas_musica` (`id_solicitud_admision` ASC) VISIBLE;

CREATE INDEX `fk_Pruebas_musica_Especificacion_lugar_prueba1_idx` ON `mydb`.`Pruebas_musica` (`id_lugar_prueba_1` ASC, `descripcion_especifica_lugar_prueba_1` ASC) VISIBLE;

CREATE INDEX `fk_Pruebas_musica_Especificacion_lugar_prueba2_idx` ON `mydb`.`Pruebas_musica` (`id_lugar_prueba_2` ASC, `descripcion_especifica_lugar_prueba_2` ASC) VISIBLE;

CREATE INDEX `fk_Pruebas_musica_Especificacion_lugar_prueba3_idx` ON `mydb`.`Pruebas_musica` (`id_lugar_prueba_3` ASC, `descripcion_especifica_lugar_prueba_3` ASC) VISIBLE;

CREATE INDEX `fk_Pruebas_musica_Convocatoria_musica1_idx` ON `mydb`.`Pruebas_musica` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Simulacro_extranjero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Simulacro_extranjero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Simulacro_extranjero` (
  `id_simulacro_extranjero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_solicitud_admision` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_simulacro_extranjero`),
  CONSTRAINT `fk_Simulacro_exttranjero_Solicitud_admision1`
    FOREIGN KEY (`id_solicitud_admision`)
    REFERENCES `mydb`.`Solicitud_admision_pregrado` (`id_solicitud_admision_pregrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Simulacro_exttranjero_Convocatoria_pregrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_pregrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Simulacro_exttranjero_Solicitud_admision1_idx` ON `mydb`.`Simulacro_extranjero` (`id_solicitud_admision` ASC) VISIBLE;

CREATE INDEX `fk_Simulacro_exttranjero_Convocatoria_pregrado1_idx` ON `mydb`.`Simulacro_extranjero` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Prueba_admision_pregrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prueba_admision_pregrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prueba_admision_pregrado` (
  `id_prueba_admision_pregrado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_solicitud_admision_pregrado` INT UNSIGNED NOT NULL,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_lugar_prueba` INT UNSIGNED NOT NULL,
  `descripcion_especifica_lugar_prueba` VARCHAR(45) NOT NULL,
  `Resultado_prueba_pregrado` INT UNSIGNED NULL,
  `Admitido` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id_prueba_admision_pregrado`),
  CONSTRAINT `fk_Prueba_admisión_Especificacion_lugar_prueba1`
    FOREIGN KEY (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    REFERENCES `mydb`.`Especificacion_lugar_prueba` (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prueba_admisión_Solicitud_admision1`
    FOREIGN KEY (`id_solicitud_admision_pregrado`)
    REFERENCES `mydb`.`Solicitud_admision_pregrado` (`id_solicitud_admision_pregrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prueba_admisión_Convocatoria_pregrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_pregrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Prueba_admisión_Especificacion_lugar_prueba1_idx` ON `mydb`.`Prueba_admision_pregrado` (`id_lugar_prueba` ASC, `descripcion_especifica_lugar_prueba` ASC) VISIBLE;

CREATE INDEX `fk_Prueba_admisión_Solicitud_admision1_idx` ON `mydb`.`Prueba_admision_pregrado` (`id_solicitud_admision_pregrado` ASC) VISIBLE;

CREATE INDEX `fk_Prueba_admisión_Convocatoria_pregrado1_idx` ON `mydb`.`Prueba_admision_pregrado` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Convocatoria_posgrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Convocatoria_posgrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Convocatoria_posgrado` (
  `id_convocatoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_convocatoria`),
  CONSTRAINT `fk_Convocatoria_posgrado_Convocatoria1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Programa_posgrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Programa_posgrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Programa_posgrado` (
  `id_programa_posgrado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_facultad` INT UNSIGNED NOT NULL,
  `nombre_programa_posgrado` VARCHAR(45) NOT NULL,
  `cupos_programa_posgrado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_programa_posgrado`),
  CONSTRAINT `fk_Programa_posgrado_Facultad1`
    FOREIGN KEY (`id_facultad`)
    REFERENCES `mydb`.`Facultad` (`id_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Programa_posgrado_Convocatoria_posgrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_posgrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Programa_posgrado_Facultad1_idx` ON `mydb`.`Programa_posgrado` (`id_facultad` ASC) VISIBLE;

CREATE INDEX `fk_Programa_posgrado_Convocatoria_posgrado1_idx` ON `mydb`.`Programa_posgrado` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitud_admision _posgrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Solicitud_admision _posgrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Solicitud_admision _posgrado` (
  `id_solicitud_admision_posgrado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `Aspirante_id_aspirante` INT UNSIGNED NOT NULL,
  `nombre_sede` VARCHAR(45) NOT NULL,
  `id_programa_posgrado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_solicitud_admision_posgrado`),
  CONSTRAINT `fk_Solicitud_admision _posgrado_Aspirante1`
    FOREIGN KEY (`Aspirante_id_aspirante`)
    REFERENCES `mydb`.`Aspirante` (`id_aspirante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_admision _posgrado_Programa_posgrado1`
    FOREIGN KEY (`id_programa_posgrado`)
    REFERENCES `mydb`.`Programa_posgrado` (`id_programa_posgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_admision _posgrado_Convocatoria_posgrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_posgrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitud_admision _posgrado_Sede1`
    FOREIGN KEY (`nombre_sede`)
    REFERENCES `mydb`.`Sede` (`nombre_sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Solicitud_admision _posgrado_Aspirante1_idx` ON `mydb`.`Solicitud_admision _posgrado` (`Aspirante_id_aspirante` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_admision _posgrado_Programa_posgrado1_idx` ON `mydb`.`Solicitud_admision _posgrado` (`id_programa_posgrado` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_admision _posgrado_Convocatoria_posgrado1_idx` ON `mydb`.`Solicitud_admision _posgrado` (`id_convocatoria` ASC) VISIBLE;

CREATE INDEX `fk_Solicitud_admision _posgrado_Sede1_idx` ON `mydb`.`Solicitud_admision _posgrado` (`nombre_sede` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Convocatoria_cine_y_television`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Convocatoria_cine_y_television` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Convocatoria_cine_y_television` (
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `fecha_prueba_cine_y_television` DATETIME NOT NULL,
  `nota_pasar_prueba_cine_y_television` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_convocatoria`),
  CONSTRAINT `fk_Convocatoria_cine_y_television_Convocatoria_pregrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_pregrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Convocatoria_cine_y_television_Convocatoria_pregrado1_idx` ON `mydb`.`Convocatoria_cine_y_television` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Prueba_cine_y_television`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prueba_cine_y_television` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prueba_cine_y_television` (
  `id_prueba_cine_y_television` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_solicitud_admision` INT UNSIGNED NOT NULL,
  `resultado_prueba_cine_y_television` INT UNSIGNED NULL,
  `id_lugar_prueba` INT UNSIGNED NOT NULL,
  `descripcion_especifica_lugar_prueba` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_prueba_cine_y_television`),
  CONSTRAINT `fk_Prueba_cine_y_television_Solicitud_admision1`
    FOREIGN KEY (`id_solicitud_admision`)
    REFERENCES `mydb`.`Solicitud_admision_pregrado` (`id_solicitud_admision_pregrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prueba_cine_y_television_Especificacion_lugar_prueba1`
    FOREIGN KEY (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    REFERENCES `mydb`.`Especificacion_lugar_prueba` (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prueba_cine_y_television_Convocatoria_cine_y_television1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_cine_y_television` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Prueba_cine_y_television_Solicitud_admision1_idx` ON `mydb`.`Prueba_cine_y_television` (`id_solicitud_admision` ASC) VISIBLE;

CREATE INDEX `fk_Prueba_cine_y_television_Especificacion_lugar_prueba1_idx` ON `mydb`.`Prueba_cine_y_television` (`id_lugar_prueba` ASC, `descripcion_especifica_lugar_prueba` ASC) VISIBLE;

CREATE INDEX `fk_Prueba_cine_y_television_Convocatoria_cine_y_television1_idx` ON `mydb`.`Prueba_cine_y_television` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Convocatoria_artes_plasticas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Convocatoria_artes_plasticas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Convocatoria_artes_plasticas` (
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `fecha_prueba_artes_plasticas` DATETIME NOT NULL,
  `nota_pasar_prueba_artes_plasticas` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_convocatoria`),
  CONSTRAINT `fk_Convocatoria_artes_plasticas_Convocatoria_pregrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_pregrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prueba_artes_plasticas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prueba_artes_plasticas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prueba_artes_plasticas` (
  `id_prueba_artes_plasticas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_solicitud_admision` INT UNSIGNED NOT NULL,
  `id_lugar_prueba` INT UNSIGNED NOT NULL,
  `descripcion_especifica_lugar_prueba` VARCHAR(45) NOT NULL,
  `resultado_prueba_artes_plasticas` INT UNSIGNED NULL,
  PRIMARY KEY (`id_prueba_artes_plasticas`),
  CONSTRAINT `fk_Prueba_artes_plasticas_Solicitud_admision1`
    FOREIGN KEY (`id_solicitud_admision`)
    REFERENCES `mydb`.`Solicitud_admision_pregrado` (`id_solicitud_admision_pregrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prueba_artes_plasticas_Especificacion_lugar_prueba1`
    FOREIGN KEY (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    REFERENCES `mydb`.`Especificacion_lugar_prueba` (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prueba_artes_plasticas_Convocatoria_artes_plasticas1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_artes_plasticas` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Prueba_artes_plasticas_Solicitud_admision1_idx` ON `mydb`.`Prueba_artes_plasticas` (`id_solicitud_admision` ASC) VISIBLE;

CREATE INDEX `fk_Prueba_artes_plasticas_Especificacion_lugar_prueba1_idx` ON `mydb`.`Prueba_artes_plasticas` (`id_lugar_prueba` ASC, `descripcion_especifica_lugar_prueba` ASC) VISIBLE;

CREATE INDEX `fk_Prueba_artes_plasticas_Convocatoria_artes_plasticas1_idx` ON `mydb`.`Prueba_artes_plasticas` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Convocatoria_programa_posgrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Convocatoria_programa_posgrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Convocatoria_programa_posgrado` (
  `id_prueba_posgrado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_programa_posgrado` INT UNSIGNED NOT NULL,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `nota_pasar_prueba_1_programa_posgrado` INT UNSIGNED NOT NULL,
  `nota_pasar_prueba_final_programa_posgrado` INT UNSIGNED NOT NULL,
  `fecha_y_hora_prueba_1_programa_posgrado` DATETIME NOT NULL,
  `fecha_y_hora_prueba_final_posgrado` DATETIME NOT NULL,
  PRIMARY KEY (`id_prueba_posgrado`),
  CONSTRAINT `fk_Convocatoria_programa_posgrado_Programa_posgrado1`
    FOREIGN KEY (`id_programa_posgrado`)
    REFERENCES `mydb`.`Programa_posgrado` (`id_programa_posgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Convocatoria_programa_posgrado_Convocatoria_posgrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_posgrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Convocatoria_programa_posgrado_Programa_posgrado1_idx` ON `mydb`.`Convocatoria_programa_posgrado` (`id_programa_posgrado` ASC) VISIBLE;

CREATE INDEX `fk_Convocatoria_programa_posgrado_Convocatoria_posgrado1_idx` ON `mydb`.`Convocatoria_programa_posgrado` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion_programa_pregrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inscripcion_programa_pregrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion_programa_pregrado` (
  `id_inscripcion_programa_pregrado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_solicitud_admision` INT UNSIGNED NOT NULL,
  `id_programa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_inscripcion_programa_pregrado`),
  CONSTRAINT `fk_Inscripcion_programa_Solicitud_admision1`
    FOREIGN KEY (`id_solicitud_admision`)
    REFERENCES `mydb`.`Solicitud_admision_pregrado` (`id_solicitud_admision_pregrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_programa_Programa1`
    FOREIGN KEY (`id_programa`)
    REFERENCES `mydb`.`Programa` (`id_programa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_programa_Convocatoria_pregrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_pregrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Inscripcion_programa_Solicitud_admision1_idx` ON `mydb`.`Inscripcion_programa_pregrado` (`id_solicitud_admision` ASC) VISIBLE;

CREATE INDEX `fk_Inscripcion_programa_Programa1_idx` ON `mydb`.`Inscripcion_programa_pregrado` (`id_programa` ASC) VISIBLE;

CREATE INDEX `fk_Inscripcion_programa_Convocatoria_pregrado1_idx` ON `mydb`.`Inscripcion_programa_pregrado` (`id_convocatoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pruebas_posgrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pruebas_posgrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pruebas_posgrado` (
  `id_pruebas_posgrado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_solicitud_admision_posgrado` INT UNSIGNED NOT NULL,
  `id_prueba_posgrado` INT UNSIGNED NOT NULL,
  `id_lugar_prueba_1_programa_posgrado` INT UNSIGNED NOT NULL,
  `descripcion_especifica_lugar_prueba_1_programa_posgrado` VARCHAR(45) NOT NULL,
  `resultado_prueba_1_programa_posgrado` INT UNSIGNED NULL,
  `id_lugar_prueba_final_programa_posgrado` INT UNSIGNED NULL,
  `descripcion_especifica_lugar_prueba_fina_programa_posgrado` VARCHAR(45) NULL,
  `resultado_prueba_final_programa_posgrado` INT UNSIGNED NULL,
  PRIMARY KEY (`id_pruebas_posgrado`, `id_prueba_posgrado`),
  CONSTRAINT `fk_Pruebas_posgrado_Solicitud_admision _posgrado1`
    FOREIGN KEY (`id_solicitud_admision_posgrado`)
    REFERENCES `mydb`.`Solicitud_admision _posgrado` (`id_solicitud_admision_posgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pruebas_posgrado_Convocatoria_programa_posgrado1`
    FOREIGN KEY (`id_prueba_posgrado`)
    REFERENCES `mydb`.`Convocatoria_programa_posgrado` (`id_prueba_posgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pruebas_posgrado_Convocatoria_posgrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_posgrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pruebas_posgrado_Especificacion_lugar_prueba1`
    FOREIGN KEY (`id_lugar_prueba_1_programa_posgrado` , `descripcion_especifica_lugar_prueba_1_programa_posgrado`)
    REFERENCES `mydb`.`Especificacion_lugar_prueba` (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pruebas_posgrado_Especificacion_lugar_prueba2`
    FOREIGN KEY (`id_lugar_prueba_final_programa_posgrado` , `descripcion_especifica_lugar_prueba_fina_programa_posgrado`)
    REFERENCES `mydb`.`Especificacion_lugar_prueba` (`id_lugar_prueba` , `descripcion_especifica_lugar_prueba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pruebas_posgrado_Solicitud_admision _posgrado1_idx` ON `mydb`.`Pruebas_posgrado` (`id_solicitud_admision_posgrado` ASC) VISIBLE;

CREATE INDEX `fk_Pruebas_posgrado_Convocatoria_programa_posgrado1_idx` ON `mydb`.`Pruebas_posgrado` (`id_prueba_posgrado` ASC) VISIBLE;

CREATE INDEX `fk_Pruebas_posgrado_Convocatoria_posgrado1_idx` ON `mydb`.`Pruebas_posgrado` (`id_convocatoria` ASC) VISIBLE;

CREATE INDEX `fk_Pruebas_posgrado_Especificacion_lugar_prueba1_idx` ON `mydb`.`Pruebas_posgrado` (`id_lugar_prueba_1_programa_posgrado` ASC, `descripcion_especifica_lugar_prueba_1_programa_posgrado` ASC) VISIBLE;

CREATE INDEX `fk_Pruebas_posgrado_Especificacion_lugar_prueba2_idx` ON `mydb`.`Pruebas_posgrado` (`id_lugar_prueba_final_programa_posgrado` ASC, `descripcion_especifica_lugar_prueba_fina_programa_posgrado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion_programa_posgrado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inscripcion_programa_posgrado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion_programa_posgrado` (
  `id_inscripcion_programa_posgrado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_convocatoria` INT UNSIGNED NOT NULL,
  `id_solicitud_admision_posgrado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_inscripcion_programa_posgrado`),
  CONSTRAINT `fk_Inscripcion_programa_posgrado_Solicitud_admision _posgrado1`
    FOREIGN KEY (`id_solicitud_admision_posgrado`)
    REFERENCES `mydb`.`Solicitud_admision _posgrado` (`id_solicitud_admision_posgrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_programa_posgrado_Convocatoria_posgrado1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `mydb`.`Convocatoria_posgrado` (`id_convocatoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Inscripcion_programa_posgrado_Solicitud_admision _posgra_idx` ON `mydb`.`Inscripcion_programa_posgrado` (`id_solicitud_admision_posgrado` ASC) VISIBLE;

CREATE INDEX `fk_Inscripcion_programa_posgrado_Convocatoria_posgrado1_idx` ON `mydb`.`Inscripcion_programa_posgrado` (`id_convocatoria` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
